### ISSUE TITLE
Check server security using the Nmap tool

### ISSUE THREAD

**Issue by tonygonzalezuk** [OpenHFT/Chronicle-Accelerate#30]
Check that the database and that ServerJVM are secure and not accessible from outside

We might want to run the Nmap tool and do a port scan and analyse security weaknesses

Only the ssh port and the Tomcat port (8080) should be available from outside

**Comment by motoras** [comment]
This is the current nmap report. I think it looks ok, the only open ports are http 80 and 8080 plus the ssh port.

Starting Nmap 7.70 ( https://nmap.org ) at 2018-03-28 11:48 EEST
Nmap scan report for s21012028.onlinehome-server.info (217.160.176.63)
Host is up (0.12s latency).
Not shown: 997 filtered ports
PORT     STATE SERVICE
22/tcp   open  ssh
80/tcp   open  http
8080/tcp open  http-proxy

Nmap done: 1 IP address (1 host up) scanned in 17.17 seconds
